### ISSUE TITLE
Exception when adding a new question to existing instance

### ISSUE THREAD

**Issue by KBorm** [drachels/moodle-mod_hotquestion#73] opened 2022-12-13 07:22 UTC
After updating to Plugin version 4.1.3 we observe an exception when adding another question to an **existing** hotquestion-instance. The question will probably be saved anyway. There are also error messages when deleting the question.
When I create a new hotquestion instance I can create a new question without problems. 

![image-2022-12-12-15-01-38-679](https://user-images.githubusercontent.com/24565300/207251964-487d37ce-0580-4671-b2a5-1fea0fcf398c.png)

**Comment by drachels** [comment] 2022-12-14 14:40
Sorry for the late reply. Yesterday was only the second time in 14 months, that I took a day off from programming and did not even turn my computer on. 
I think the problem is due to having to make some changes to the completion code, to be able to get this release out for Early Bird. Note that I have not been able to duplicate the error, but I think that if you edit the activity, and reset the completion, it might fix things. Please back up first, before trying.

**Comment by KBorm** [comment] 2022-12-14 16:01
The "Activity completion" is locked:

This activity has already been marked as completed for 62 participant(s). Changing completion options will erase their completion state and may cause confusion. Thus the options have been locked and should not be unlocked unless absolutely necessary. 

When I unlock and enter a new question the errors still occurs.

**Comment by KBorm** [comment] 2022-12-16 10:53
You can reproduce this error when you set the 'Activity completion' 'Completion tracking' field in your hotquestion instance to 'Students can manually mark the activity as completed'. 
When you enter a new question then the exception is thrown.

**Comment by drachels** [comment] 2022-12-16 14:17
Thanks for the info. I have a medical appointment I have to go to this morning, my time, so I will try to get working on it when I get back.

**Comment by drachels** [comment] 2022-12-17 16:45
I will need to do some more testing to make sure, but it looks like a workable fix is in the locallib.php file, change line 938 from this:
$completion->update_state($this->cm, COMPLETION_UNKNOWN, $user);
So that it becomes this:
$completion->set_module_viewed($cm);
As I said I will need to do some more testing, but it works on my main Moodle 4.1 development site, so far.

**Comment by drachels** [comment] 2022-12-19 18:42
Fix is included in release v4.1.4.

**Closed** 2022-12-19 18:42 UTC
