### ISSUE TITLE
CSV file cannot open in MS Excel

### ISSUE THREAD

**Issue by ckong11** [drachels/moodle-mod_hotquestion#24] opened 2017-06-23 21:16 UTC
A lot of our users tend to open CSV files in MS Excel. When I open the exported CSV file into Excel, I get two error messages "Microsoft Excel cannot convert some of the cells." I tried this on both Excel in Windows and Mac. 
 
<img width="431" alt="screen shot 2017-06-23 at 1 52 32 pm" src="https://user-images.githubusercontent.com/660792/27500694-6f654d6a-581e-11e7-96b0-5e11ca15cf75.png">
<img width="428" alt="screen shot 2017-06-23 at 1 52 51 pm" src="https://user-images.githubusercontent.com/660792/27500697-70da9e02-581e-11e7-908e-b1945798cfae.png">

The file opens in Mac's Numbers. And it opens in a wordprocess like Notepad or Text Edit.

**Comment by drachels** [comment] 2017-06-24 00:11
I need to know which version of HotQuestion, which version of Moodle, and which version of MS Excel.

**Comment by drachels** [comment] 2017-06-25 16:52
Hmm, don't need the extra info after all. Turns out the problem is with MS Excel. Any time you try to open a file where the first record is "ID" Excel will attempt to interpret the file as SYLK.
In this case, since ID is the ID of a particular HotQuestion, I have changed the order of the output fields to make ID the third item, instead of the first.
I also rewrote the code to use csv_export_writer() instead of the fopen/fputscv method that needs all the header info.
I will put out a new version in a day or two. Since I am including a bunch of new Behat tests I need to do some more testing to make sure the changes are STABLE. Plus I just thought of another Behat test I need to include.

**Comment by drachels** [comment] 2017-06-25 17:00
I have pushed the fix into current master.

**Closed by drachels** 2017-06-25 17:00 UTC

**Comment by ckong11** [comment] 2017-07-05 23:21
@drachels is there any way you can include this patch into the MOODLE_311_STABLE branch? I see it in master, but we're running Moodle 3.1 and master might not be compatible with our version of Moodle. Thanks!!!

**Comment by drachels** [comment] 2017-07-06 14:39
I will try to back port the changes to all the versions but will probably not be able to do that until the week end. Got construction workers here for the next two days adding gutters to the house and workshop, plus I am in the middle of painting the interior of my new workshop. Also have to install baseboards and corner molding. Just remembered, haven't order the wood and quarter round trim for that yet.

If you can't wait, copy the download_questions function in the locallib.php file for HotQUestion 3.3 and use it to replace the download_questions function in locallib.php file for HotQuestion 3.1.

**Comment by ckong11** [comment] 2017-07-06 17:26
No worries! I believe we can wait and thanks for the tip about copying the download_questions function in locallib.php.

Good luck on the house work!!

**Comment by drachels** [comment] 2017-07-08 15:24
I must be sicker than I thought to not realize this sooner...HotQuestion Version 3.2.2 can be installed in place of your 3.1.1 version and it has the changes in it to the CSV code. In fact, 3.2.2 is the version I am using on my Moodle 3.1.6+ development and testing site. As a further note, the only difference between HQ 3.2.2 and HQ 3.3.0 is the change from using pix_url to image_url in a couple of places.

**Comment by ckong11** [comment] 2017-07-10 17:00
Good to know. Thanks @drachels!!
